# datetime64

In [2]:
# numpy's native way to store dates and times efficiently.
import numpy as np

date1=np.datetime64('2025-01-01')
date2=np.datetime64('2025-01-01 14:30:00')

# Date units (precision)
# 'Y' = Year  'M'= Month  'D'= Day
# 'h' = Hour  'm'= minute 's'= Second
date_day=np.datetime64('2025-01-01','D')     # just day
date_hour=np.datetime64('2025-01-01 14','h') # hours precision

# Arithmetic with datetime64
tomorrow=date1+np.timedelta64(1,'D')
next_week=date1+7   # 'D' - default while adding integers

# Key points:
# Fast and memory efficient
# Supports date math
# Limited functionality (no direct .dayofweek)

# pd.to_datetime() (Pandas converter)

In [12]:
import pandas as pd
# converting strings to datetime
dates1=pd.to_datetime(['2025-01-01','2025-01-02','2025-01-03'])

# converts Numbers (Unix timestamp)
dates2=pd.to_datetime([1672531200, 1672617600], unit='s')

# converts mixed formats
dates3=pd.to_datetime(['2025-01-01','Jan 2, 2025', '20250103'], format='mixed')

# Handles errors gracefully
dates4=pd.to_datetime(['2025-01-01','invalid','2025-01-03'], errors='coerce')
# here invalid becomes NaT (Not a Time)

# From numpy datetime64
np_dates=np.array(['2025-01-01','2025-01-02'],dtype='datetime64[D]')
pd_dates=pd.to_datetime(np_dates)

# Why use it? NumPy's datetime64 is limited. Pandas datetime gives you more methods.

# .dayofweek (Day of Week as Number)
What it does: Returns Monday=0, Tuesday=1, ..., Sunday=6

In [5]:
import pandas as pd
dates=pd.to_datetime(['2025-01-01','2025-01-02','2025-01-03'])
# 2025-01-01 was wednesday

# Get day of week (0=monday, 1=tuesday, 2=wednesday)
dow=dates.dayofweek
print(dow) # [2,3,4]  (Wed=2)
# if we need 1=monday, 2=tuesday
# simply
dow=dates.dayofweek + 1

# to get week day name
day_names=dates.day_name() # ['Wednesday','Thursday','Friday']

Index([2, 3, 4], dtype='int32')


# .isocalendar() (ISO Week Calendar)

In [10]:
# returns (yearm week_number, weekday) where weekday=1 (Monday) to 7(Sunday)
import pandas as pd
dates=pd.to_datetime(['2025-01-01','2025-01-02'])

# Get ISO calendar info
iso=dates.isocalendar()
print(iso)

# accessing individual components
iso_year=dates.isocalendar().year
iso_week=dates.isocalendar().week
iso_weekday=dates.isocalendar().day
print(iso_year,iso_week,iso_weekday)

# Use .day for weekday (instead of .dayofweek)

            year  week  day
2025-01-01  2025     1    3
2025-01-02  2025     1    4
2025-01-01    2025
2025-01-02    2025
Name: year, dtype: UInt32 2025-01-01    1
2025-01-02    1
Name: week, dtype: UInt32 2025-01-01    3
2025-01-02    4
Name: day, dtype: UInt32


# timedelta64 

In [13]:
# datetime64-- a specific point in time
date=np.datetime64('2025-01-01 13:00:00')

# timedelta64-- a duration or interval
duration = np.timedelta64(45,'m') # 45 minutes

# what is overflow ? 
uint8 can only store values from 0 to 255. if a value exceeds 255, it wraps around (overflow)

In [15]:
# e.g.
overflow_eg=np.array([250,255,256], dtype=np.uint8)
print(overflow_eg)

OverflowError: Python integer 256 out of bounds for uint8

# .any()-
checks if any elements in the boolean array is True. returns - True if atleast one True exists, otherwise False.

In [ ]:
import numpy as np

# Example 1: No overflow
overflow_positions = np.array([False, False, False, False])
print(overflow_positions.any())  # False (no True values)

# Example 2: Some overflow
overflow_positions = np.array([False, True, False, False])
print(overflow_positions.any())  # True (at least one True)

# Example 3: All overflow
overflow_positions = np.array([True, True, True, True])
print(overflow_positions.any())  # True (still True)

# when formats of a row and its elements are given in operations, loop can be used to make an array

In [ ]:
# condition- there should be 15 rows containing 4 elements in each row in format = (i,i**2,i**3,i**4)
# instead of making every column first and then using concatenate we can simply use this :
obj_arr=np.array([
    [i,i**2,i**3,i**4] for i in range(1,16)
], dtype=object)
print(obj_arr)

# what is bitwise

# to know the limits of a dtype

In [2]:
import numpy as np
# use .iinfo()
# e.g. 
int16_min=np.iinfo(np.int16).min
int16_max=np.iinfo(np.int16).max
print(int16_min,int16_max)

-32768 32767


# np.newaxis trick

In [2]:
# a trick to add a new axis in the array- its like adding a new dimension at a specific position
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.shape)

# add new axis at position 0 (make it a row vector)
row_vec=arr[np.newaxis, : ]
print(row_vec.shape)

# add new axis at position 1 (makes it a column vector)
col_vec=arr[:, np.newaxis]
print(col_vec.shape)

(5,)
(1, 5)
(5, 1)


### common use case

In [3]:
# 1. converting 1D to column vector (for broadcasting)

# without newaxis- cant broadcast properly
a=np.array([1,2,3])
b=np.array([4,5,6])
# a+b works fine (both 1D)

# But for matrix operations, you need specific shapes
col=a[ : ,np.newaxis]
row=b[np.newaxis, : ]

# 2. Maing Arrays Broadcast-Compatible

#  Problem: Add a 1D array to each row of a 2D array
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# without newaxis- Error (shapes (3,3) and (3,) incompatible 
# result=matirx + row_to_add # wrong !

# 3. Creating Grids for Computation
# Create coordinate grids without meshgrid
x = np.linspace(0, 10, 5)      # shape (5,)
y = np.linspace(0, 10, 4)      # shape (4,)

# Create 2D grid using newaxis
X = x[np.newaxis, :]   # shape (1, 5)
Y = y[:, np.newaxis]   # shape (4, 1)

# Now broadcast to create full grid
grid = X + Y  # shape (4, 5) - every combination!

In [ ]:
# alternate syntax : None
# np.newaxis is exactly the same as writting None
# These are identical:
arr[:,np.newaxis]
arr[:,None]

# Column Weights meaning

In [ ]:
# e.g.
# imagine you have a table with 100 rows and 50 columns


# Stride Broadcasting

# np.outer()

# zip()

In [2]:
names=['A','B','C']
values=[10,20,30]
result=zip(names,values)
print(list(result))

[('A', 10), ('B', 20), ('C', 30)]


# np.any()

# np.allclose()

# setting a random seed 

In [ ]:
np.random.seed(10)

# Normal Distribution representation
N(mean, std.deviation)

# Changing Normal Distribution
fron default- N(0,1)where this is N(mean, std.deviation) to N(any number, any number).
N(0,1) can be stretched and moved to become any normal distribution.

# np.random.choice()

In [1]:
# EXAMPLE

import numpy as np

np.random.seed(42)

# Pick 3 numbers from 1-10 (can repeat)
a = np.random.choice(10, size=3, replace=True)
print(a)  # [7 4 8] (numbers 0-9)

# Pick 3 numbers from 1-10 (no repeats)
b = np.random.choice(10, size=3, replace=False)
print(b)  # [7 4 8] (all different)

# Pick from custom list
c = np.random.choice([10, 20, 30, 40, 50], size=2, replace=False)
print(c)  # [40 10]

# Lottery example: 6 unique numbers from 1-49
lotto = np.random.choice(range(1, 50), size=6, replace=False)
print(lotto)  # [14 46 48 45 18 28]

[6 3 7]
[9 7 0]
[50 40]
[37 17  5 10 46 41]


# np.random.permutation()

In [ ]:
# EXAMPLE

import numpy as np

np.random.seed(42)

# Permutation of a range
a = np.random.permutation(10)
print(a)  # [8 1 5 0 7 2 9 4 3 6] (0-9 shuffled)

# Permutation of an existing array
arr = np.array([10, 20, 30, 40, 50])
b = np.random.permutation(arr)
print(b)  # [40 10 50 30 20]

# Original array unchanged
print(arr)  # [10 20 30 40 50] ← NOT changed!

# np.random.shuffle()

In [ ]:
# EXAMPLE

import numpy as np

np.random.seed(42)

# Shuffle an existing array (in-place)
arr = np.array([10, 20, 30, 40, 50])
np.random.shuffle(arr)
print(arr)  # [40 10 50 30 20] ← original IS changed!

# Shuffle a list of numbers
arr2 = [1, 2, 3, 4, 5, 6]
np.random.shuffle(arr2)
print(arr2)  # [4, 5, 6, 2, 3, 1]

# Saving and Loading NumPy Arrays

# np.savetxt() and np.loadtxt() functions

In [5]:
array=np.arange(12).reshape(3,4)
np.savetxt('array.txt', array, delimiter=',', fmt='%.1f')

# formatting

In [ ]:
%[flags][width][.precision]type

In [ ]:
# Integer
print("%d" % 42)        # 42

# Float
print("%f" % 3.14159)   # 3.141590
print("%.2f" % 3.14159) # 3.14
print("%.4f" % 3.14)    # 3.1400

# Scientific
print("%e" % 12345)     # 1.234500e+04
print("%.2e" % 12345)   # 1.23e+04

# Multiple values
print("%d, %.2f, %s" % (10, 3.14159, "hello"))
# 10, 3.14, hello

# np.tolist()

# slice operator

# np.pad

# np.intersected1d

In [ ]:
result = np.intersect1d([5, 1, 3], [3, 1, 7])
print(result)  # [1 3]  (sorted)

In [2]:
import numpy as np
A_2d = np.array([[1, 2], [3, 4]])
B_2d = np.array([[3, 5], [1, 6]])
result = np.intersect1d(A_2d, B_2d)  # [1 3]

In [4]:
common, idx_a, idx_b = np.intersect1d(A_2d, B_2d, return_indices=True)
print("Common:", common)
print("Indices in A:", idx_a)
print("Indices in B:", idx_b)

Common: [1 3]
Indices in A: [0 2]
Indices in B: [2 0]


# np.unique