# Questions on Creating Arrays with Specific Data Types

## Basic 

In [7]:
import numpy as np
arr1=np.arange(0,20,dtype=np.float16).reshape(4,5)
print(f"arr1: \n{arr1}")
print(f"dtype: {arr1.dtype}")
arr2=arr1.astype(np.float32)
print(f"dtype now: {arr1.dtype}")
print("-----------------------------------")

arr1_recovered=arr2.astype(np.float16)
loss = arr1_recovered-arr1
print(f"arr1: \n{arr1}")
print(f"arr2: \n{arr2}")
print(f"arr1_recovered: \n{arr1_recovered}")
print(f"loss : \n{loss}")
print(f"cumulatve precision loss: {np.sum(loss)}")

arr1: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
dtype: float16
dtype now: float16
-----------------------------------
arr1: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
arr2: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
arr1_recovered: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
loss : 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
cumulatve precision loss: 0.0


In [35]:
students= np.array(
    [('Alice', 85, 8.5),
    ('Bob', 92, 8.2),
    ('Charlie', 78, 7.9),
    ('Diana', 92, 8.8),
    ('Eve', 85, 9.0)],
    dtype= [('name', 'U10'), ('score', 'uint8'), ('grade', 'f4')])
print(students)
print("_"*50)

# sorting
# ascending
students_ascending=np.sort(students,order='score')
print(students_ascending)

# descending
print(f"descending sorted students: \n{students_ascending[::-1]}")

[('Alice', 85, 8.5) ('Bob', 92, 8.2) ('Charlie', 78, 7.9)
 ('Diana', 92, 8.8) ('Eve', 85, 9. )]
__________________________________________________
[('Charlie', 78, 7.9) ('Alice', 85, 8.5) ('Eve', 85, 9. ) ('Bob', 92, 8.2)
 ('Diana', 92, 8.8)]
descending sorted students: 
[('Diana', 92, 8.8) ('Bob', 92, 8.2) ('Eve', 85, 9. ) ('Alice', 85, 8.5)
 ('Charlie', 78, 7.9)]


In [59]:
arr1=np.arange(0,60).reshape(3,4,5)
comp_arr1=arr1.astype(np.complex128)
complex_squares_array=comp_arr1+(comp_arr1*comp_arr1)*1j
np.set_printoptions(suppress=True, precision=0)
print(final_result)

[[[ 0.   +0.j  1.   +1.j  2.   +4.j  3.   +9.j  4.  +16.j]
  [ 5.  +25.j  6.  +36.j  7.  +49.j  8.  +64.j  9.  +81.j]
  [10. +100.j 11. +121.j 12. +144.j 13. +169.j 14. +196.j]
  [15. +225.j 16. +256.j 17. +289.j 18. +324.j 19. +361.j]]

 [[20. +400.j 21. +441.j 22. +484.j 23. +529.j 24. +576.j]
  [25. +625.j 26. +676.j 27. +729.j 28. +784.j 29. +841.j]
  [30. +900.j 31. +961.j 32.+1024.j 33.+1089.j 34.+1156.j]
  [35.+1225.j 36.+1296.j 37.+1369.j 38.+1444.j 39.+1521.j]]

 [[40.+1600.j 41.+1681.j 42.+1764.j 43.+1849.j 44.+1936.j]
  [45.+2025.j 46.+2116.j 47.+2209.j 48.+2304.j 49.+2401.j]
  [50.+2500.j 51.+2601.j 52.+2704.j 53.+2809.j 54.+2916.j]
  [55.+3025.j 56.+3136.j 57.+3249.j 58.+3364.j 59.+3481.j]]]


In [81]:
arr1=np.arange(1,101).reshape(10,10)
print(arr1)
print("_"*70)

rows=np.arange(10).reshape(10,1)
cols=np.arange(10).reshape(1,10)
product=rows*cols
cond_a=(product%7==0)
print(cond_a)
print("_"*70)

sum_=rows+cols
cond_b=(sum_%5==0)
print(cond_b)
print("_"*70)

result=cond_a | cond_b
print(result)
print(np.where(result==True,arr1,'[]'))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
______________________________________________________________________
[[ True  True  True  True  True  True  True  True  True  True]
 [ True False False False False False False  True False False]
 [ True False False False False False False  True False False]
 [ True False False False False False False  True False False]
 [ True False False False False False False  True False False]
 [ True False False False False False False  True False False]
 [ True False False False False False False  True False False]
 [ True  True  True  True  True  True  True  True  True  

In [90]:
import numpy as np
import pandas as pd

arr=np.datetime64('2025-01-01')
dates=arr+np.arange(20)*3
print(dates)

pd_dates=pd.to_datetime(dates)
print(pd_dates)
dow=pd_dates.dayofweek
dow_iso=pd_dates.isocalendar().day

['2025-01-01' '2025-01-04' '2025-01-07' '2025-01-10' '2025-01-13'
 '2025-01-16' '2025-01-19' '2025-01-22' '2025-01-25' '2025-01-28'
 '2025-01-31' '2025-02-03' '2025-02-06' '2025-02-09' '2025-02-12'
 '2025-02-15' '2025-02-18' '2025-02-21' '2025-02-24' '2025-02-27']
DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16', '2025-01-19', '2025-01-22',
               '2025-01-25', '2025-01-28', '2025-01-31', '2025-02-03',
               '2025-02-06', '2025-02-09', '2025-02-12', '2025-02-15',
               '2025-02-18', '2025-02-21', '2025-02-24', '2025-02-27'],
              dtype='datetime64[s]', freq=None)
Index([2, 5, 1, 4, 0, 3, 6, 2, 5, 1, 4, 0, 3, 6, 2, 5, 1, 4, 0, 3], dtype='int32')
2025-01-01    3
2025-01-04    6
2025-01-07    2
2025-01-10    5
2025-01-13    1
2025-01-16    4
2025-01-19    7
2025-01-22    3
2025-01-25    6
2025-01-28    2
2025-01-31    5
2025-02-03    1
2025-02-06    4
2025-02-09    7
2025-02-12    3
2025-02-

In [26]:
import numpy as np
mins=np.random.randint(30,301, size=100)
intervals=mins.astype('timedelta64[m]')

# conversion to timedelta64 minutes
print(intervals[:5])

# conversion to hours as floats
hours=(np.float32(intervals)/60.0)
hours_rounded=np.round(hours,2)
print(hours_rounded[:5])

[213  84 232 126 216]
[3.55 1.4  3.87 2.1  3.6 ]


In [46]:
import numpy as np
arr1=np.arange(1,7).reshape(1,6)
col=np.arange(31,37).reshape(6,1)
table=arr1*col
print(f"table: \n{table}")
print()

print("# checking for overflow...")
print()

table_twice=table*2
print(f"table x 2: \n{table_twice}")
overflow_state=np.any(table_twice>255)
print()

if overflow_state:
    print(f"overflow detected at : \n{np.argwhere(table_twice>255)}")
else:
    print("no overflow")

table: 
[[ 31  62  93 124 155 186]
 [ 32  64  96 128 160 192]
 [ 33  66  99 132 165 198]
 [ 34  68 102 136 170 204]
 [ 35  70 105 140 175 210]
 [ 36  72 108 144 180 216]]

# checking for overflow...

table x 2: 
[[ 62 124 186 248 310 372]
 [ 64 128 192 256 320 384]
 [ 66 132 198 264 330 396]
 [ 68 136 204 272 340 408]
 [ 70 140 210 280 350 420]
 [ 72 144 216 288 360 432]]

overflow detected at : 
[[0 4]
 [0 5]
 [1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]
 [3 3]
 [3 4]
 [3 5]
 [4 3]
 [4 4]
 [4 5]
 [5 3]
 [5 4]
 [5 5]]


In [18]:
import numpy as np
# my solution

# col_1=(np.arange(1,16).reshape(-1,1)).astype('object')
# col_2=(np.arange(1,16).reshape(-1,1)**2).astype('object')
# col_3=(np.arange(1,16).reshape(-1,1)**3).astype('object')
# col_4=(np.arange(1,16).reshape(-1,1)**4).astype('object')
# final_table=np.concatenate((col_1,col_2,col_3,col_4), axis=1)
# print(final_table)
# cubes=final_table([:,2:3]).astype(np.float32)


# better approach

obj_arr=np.array([
    [i,i**2,i**3,i**4] for i in range(1,16)
], dtype=object)
print(obj_arr)
print(obj_arr.dtype)

# cubes extraction
cubes=obj_arr[:,2]
cubes=obj_arr[:,2:3]
print(cubes)

[[1 1 1 1]
 [2 4 8 16]
 [3 9 27 81]
 [4 16 64 256]
 [5 25 125 625]
 [6 36 216 1296]
 [7 49 343 2401]
 [8 64 512 4096]
 [9 81 729 6561]
 [10 100 1000 10000]
 [11 121 1331 14641]
 [12 144 1728 20736]
 [13 169 2197 28561]
 [14 196 2744 38416]
 [15 225 3375 50625]]
object
[[1]
 [8]
 [27]
 [64]
 [125]
 [216]
 [343]
 [512]
 [729]
 [1000]
 [1331]
 [1728]
 [2197]
 [2744]
 [3375]]


# THE REAL GAME 
# BROADCASTING - Complete Mastery Set

# Basic

## Rule 1: Basic Shape Compatibility

In [ ]:
# 1. Will these broadcast? Why or why not?
a.shape = (6, 1)
b.shape = (5,)

In [ ]:
# 2. Will these broadcast? If yes, what's the output shape?
a.shape = (3, 4, 5)
b.shape = (4, 5)

In [ ]:
# 3. Will these broadcast? Explain the rule violation.
a.shape = (2, 3, 4)
b.shape = (3, 5)