In [1]:
import numpy as np
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])
D = np.array([0.1, 0.3])

for name,array in zip(list('ABCD'),[A,B,C,D]):
    print(f"{name}:{np.all(array)}")

A:True
B:False
C:False
D:True


In [2]:
import numpy as np

A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])

for name,value in zip(list('ABC'),[A,B,C]):
    print(f"{name}: {np.all(value,axis=1)}")

A: [ True  True]
B: [ True False]
C: [False  True]


In [3]:
import numpy as np
A = np.array([[0, 0, 0],
              [0, 0, 0]])
B = np.array([[0, 0, 0],
              [0, 1, 0]])
C = np.array([[False, False, False],
              [True, False, False]])
D = np.array([[0.1, 0.0]])

for name,value in zip(list('ABCD'),[A,B,C,D]):
    print(f"{name}: {np.any(value)}")

A: False
B: True
C: True
D: True


In [4]:
import numpy as np
A = np.array([[0, 0, 0],
              [0, 0, 0]])
B = np.array([[0, 0, 0],
              [0, 1, 0]])
C = np.array([[False, False, False],
              [True, False, False]])
D = np.array([[0.1, 0.0]])

for name, value in zip(list('ABCD'),[A,B,C,D]):
    print(f"{name}: {np.any(value,axis=0)}")

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


In [5]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [6]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
print(np.allclose(A,B))

True


In [7]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

comparision=(A==B)
print(comparision)

# other way
print(np.equal(A,B))

[False False  True]
[False False  True]


In [8]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
# way 1
greater_A=np.where(A>B,True, False)
print(greater_A)

# way 2
print(A>B)

# way 3
print(np.greater(A,B))

[ True False False False]
[ True False False False]
[ True False False False]


In [9]:
arr=np.zeros((4,4),dtype='int')
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
arr=np.ones((10,10),dtype='int')
print(arr*255)

print("-"*50)
arr=np.full(100,255).reshape(10,10)
print(arr)

[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]
--------------------------------------------------
[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


In [11]:
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [12]:
print(np.arange(10,100).reshape(9,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
print(np.eye(6,6,dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [14]:
np.random.seed(10)
arr=np.random.rand(30)
print(arr)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


In [15]:
np.random.seed(20)
arr=np.random.randn(40).reshape(10,4)
print(arr)

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


In [16]:
import numpy as np
np.random.seed(30)
arr=100 + 5*np.random.randn(10,4)
print(arr)

[[ 93.67973668 107.63952676  95.14644531 102.35279808]
 [ 99.49651642 101.51896592  91.37018786 107.92547685]
 [100.67148297  94.46572267 107.89112775 100.53748971]
 [ 96.17976087  96.12405745 106.91923583 103.80192542]
 [ 98.57177243 102.69183738  89.58051684 104.68890855]
 [ 99.97111002  97.66260516  97.8849235  105.32241047]
 [ 85.48316202 108.08445187 107.12754943  96.67622441]
 [104.9250893   91.49767367  94.49928096  93.42177955]
 [104.05250455  94.77610813  96.55385313  95.73621568]
 [105.56736054  90.39415141  96.49298791 104.24543925]]


In [17]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])     # the given array
for element in np.nditer(A):      # nditer iterates through the array
    print(element)

1
4
3
5
2
6


In [18]:
print(np.linspace(start=0, stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [19]:
import numpy as np

np.random.seed(42)
numbers=np.arange(1,50)
result=np.random.choice(numbers,size=6)
print(result)

[39 29 15 43  8 21]


In [20]:
arr=np.diag(np.arange(6))
print(arr)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [21]:
arr=np.arange(12).reshape(3,4)
np.save('array.npy',arr)

loaded_arr=np.load('array.npy')
print(loaded_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
arr=np.arange(12,dtype='int').reshape(3,4)
np.savetxt('array.txt',arr)
loaded_txt=np.loadtxt('array.txt')
print(loaded_txt)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [23]:
import numpy as np
arr=np.arange(12).reshape(3,4)
lst=arr.tolist()
print(lst)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [24]:
import numpy as np

arr=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

print(arr[::-1,:])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [25]:
arr=np.array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

padded=np.pad(arr,pad_width=1, mode='constant')
print(padded)
print()
padded=np.pad(arr,pad_width=((1,2),(3,4)))
print(padded)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
import numpy as np

arr=np.zeros((6,6))
arr[::2,::2]=10
arr[1::2,::2]=5
print(arr)

[[10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]
 [10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]
 [10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]]


In [27]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
appended=np.append(A,B,axis=0)
print(appended)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [28]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])
intersected=np.intersect1d(A,B)
print(intersected)

[0 2 3]


In [29]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

unique=np.unique(A)
print(unique)

[1 2 4 5 7 9]


In [30]:
import numpy as np
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
print(np.argmax(A, axis=1))

[0 2 1]


In [31]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])

# sorting by row
row_sorted= np.sort(A, axis=1)
column_sorted=np.sort(A, axis=0)

print(row_sorted)
print(column_sorted)

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [32]:
A = np.array(
    [[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]]
)
print(A[A>8])

[ 9.99  9.99 14.99]


In [33]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

# using np.where method

replaced=np.where(A<10, A, 10.0)
print(replaced)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


In [34]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


In [35]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
import numpy as np

A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)
new_arr=np.full_like(A,9.99)
print(new_arr)

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


In [37]:
print(np.tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [38]:
A=np.arange(1,25).reshape(2,3,4)
print(A)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [39]:
arr=np.random.randint(0, 255, size=60000, dtype=np.uint8).reshape(200,300)
print(arr)

[[102 214 240 ... 195 126   7]
 [ 67  76 213 ... 166  40 152]
 [169  29  27 ... 205 107 182]
 ...
 [208 182  63 ... 213 251 192]
 [205 154 103 ... 220  95  70]
 [117  54  55 ...  59 126  57]]


In [40]:
image = np.random.randint(
    low=0, high=256, size=(200, 300), dtype=np.uint8
)

image_sorted=np.sort(image, axis=1)
print(image_sorted)

[[  0   1   2 ... 254 255 255]
 [  0   0   0 ... 254 255 255]
 [  1   2   2 ... 253 254 255]
 ...
 [  0   3   3 ... 252 255 255]
 [  0   1   5 ... 255 255 255]
 [  0   1   2 ... 253 254 254]]


In [41]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])
expanded=A[None,:,:]
print(expanded.shape)

print(np.expand_dims(A, axis=0))

(1, 2, 3)
[[[4 2 1]
  [6 4 2]]]


In [42]:
np.random.seed=42
image=np.random.randint(0,255, size=180000, dtype=np.uint8).reshape(200,300,3)
print(image)

[[[218  50  78]
  [186 195 240]
  [ 57 235  73]
  ...
  [135  97  60]
  [176 183 140]
  [220  16 212]]

 [[ 12  58 196]
  [219 203 181]
  [ 11 232   1]
  ...
  [177 129 141]
  [239 136  43]
  [215 204  25]]

 [[121 205 144]
  [  2 225  72]
  [164  99   3]
  ...
  [ 46 210  47]
  [226 210  58]
  [121 209 181]]

 ...

 [[130 221 246]
  [ 28 159 247]
  [140 108 137]
  ...
  [245 192  39]
  [205 139  79]
  [238 195 120]]

 [[226 188 174]
  [197 235  22]
  [211 234 228]
  ...
  [ 87 149  57]
  [ 96 122 202]
  [119 121 163]]

 [[  4 134  95]
  [231  21  92]
  [ 97 208 206]
  ...
  [ 65 155 143]
  [  1 151 174]
  [150  53 213]]]


In [43]:
import numpy as np

image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

new_image= np.expand_dims(image, axis=0)
print(new_image.shape)

(1, 200, 300, 3)


In [44]:
image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

new_image1=np.expand_dims(image1, axis=0)
new_image2=np.expand_dims(image2, axis=0)

combined=np.concatenate([new_image1, new_image2], axis=0)
print(combined.shape)

(2, 200, 300, 3)


In [45]:
A = np.array([[[1, 2, 3], [6, 3, 2]]])
np.squeeze(A)

array([[1, 2, 3],
       [6, 3, 2]])

In [46]:
A = np.array([[0.4], [0.9], [0.5], [0.6]])
np.squeeze(A)

array([0.4, 0.9, 0.5, 0.6])

In [47]:
arr=np.array(
    [
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]
    ]
)
transformed=arr[:,::-1]
print(transformed)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [48]:
a=np.array(
    [
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]
    ]
)
print(a[::-1,::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [49]:
np.random.seed(42)

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

print(image[0,::,::])

TypeError: 'int' object is not callable

In [ ]:
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

result= image[0:5:,0:5:,::]
print(result.shape)

In [ ]:
A = np.array([[3, 4, 5], [8, 3, 1]])
B = np.array([[0, 5, 2], [4, 2, 1]])

print(np.concatenate((A,B), axis=0))

In [ ]:
import numpy as np

data = np.array([[4.3, 4.2], [3.1, 3.6]])
target = np.array([[0], [1]])

together=np.concatenate((data, target), axis=1)
print(together)

In [ ]:
feature1 = np.array([1.6, 0.9, 2.2]).reshape(-1,1)
feature2 = np.array([0.4, 1.3, 3.2]).reshape(-1,1)
feature3 = np.array([1.4, 0.3, 1.2]).reshape(-1,1)
print(np.concatenate((feature1, feature2, feature3), axis=1))

In [ ]:
arr=np.array(
    [
        [0, 0, 4, 6, 2, 4, 1, 1],
        [0, 0, 6, 2, 2, 4, 1, 1],
        [0, 0, 1, 3, 5, 5, 1, 1],
        [0, 0, 3, 1, 5, 4, 1, 1],
        [0, 0, 2, 6, 1, 3, 1, 1]
    ]
)
A1,A2,A3=np.split(arr,[2,6],axis=1)
print(A1)
print(A2)
print(A3)

In [ ]:
np.random.seed(42)
A = np.random.randint(low=0, high=2, size=(10, 6))
print(np.count_nonzero(A))

In [ ]:
np.random.seed(42)
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
print(A)

In [ ]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)
print(A)

In [ ]:
np.random.seed(42)

A = np.random.randn(8, 4)
deleted=np.delete(A,2,axis=1)
print(deleted)

In [ ]:
v = np.array([3, 4, -2])
norm=np.sqrt(np.sum(v**2))
print(norm)

norm2=np.linalg.norm(v)
print(norm2)



In [ ]:
import numpy as np

np.random.seed(42)
A = np.random.randint(10, size=(100, 30))

np.set_printoptions(edgeitems=10)
print(A)

In [ ]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

mean=(A+B)/2
print(mean)

In [ ]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

multi=np.multiply(A,B)
print(multi)

In [ ]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])

print(np.sqrt(A))

In [ ]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

pytho_theorum=(np.sin(A))**2+(np.cos(A))**2
print(pytho_theorum)
print(B)

print(pytho_theorum is B)  # False because of floating point precision.
print(np.allclose(pytho_theorum, B)) # True because np.allclose ignores the floating point precision difference

In [ ]:
A = np.array([[2, 3], [-4, 2], [5, 0]])
B = np.array([[4, 3, 2], [-1, 0, 2]])

print(np.dot(A,B))

In [ ]:
A = np.array([[-2, 0, 4], [5, 2, -1], [-4, 2, 4]])

print(np.linalg.det(A))

In [ ]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

eigenvalues, eigenvectors= np.linalg.eig(A)


In [ ]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
print(np.linalg.inv(A))

In [ ]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

print(np.trace(A))

In [ ]:
A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

B=B.reshape(2,4)
print(np.dot(A,B))

In [ ]:
A = np.array(
    [
        ['id', 'price'],
        ['001', 14.99],
        ['002', 4.99],
        ['003', 7.99],
        ['004', 2.49],
        ['005', 1.49],
    ]
)
np.random.shuffle(A)
print(A)

In [ ]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

print(np.argsort())

In [ ]:
import numpy as np

np.random.seed(42)
A = np.random.randn(10, 8)
print(np.round(A, 3))

In [ ]:
print(np.roots([4,5,1]))

In [ ]:
print(np.roots([2,4,-5,1]))
print(np.roots([2,0,-5,1]))

In [ ]:
W = [0,4,5,1]
Q = [2,4,-5,1]

print(np.polyadd(W,Q))
print(np.polysub(W,Q))
print(np.polymul(W,Q))
print(np.polyadd(W,np.polymul(2,Q)))

In [ ]:
A = np.array([[-4, 3, 0, 1, -5], 
              [6, -4, -2, 1, 3]])
print(np.sign(A))

In [ ]:
dates=np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]')
print(dates)
print("-"*50)
# alternatvie
start=np.datetime64('2021-01-01')
dates=start + np.arange(31)
print(dates)

In [ ]:
dates=np.arange('2021-01','2022-01',dtype='datetime64[M]').reshape(4,3)
print(dates)

In [ ]:
print(np.datetime64('today'))

In [ ]:
# first approach
'''
dates=np.arange('2020-01-01', '2020-03-01', dtype='datetime64[D]')
mask= dates=='Monday'
print(np.where(mask))
'''

# 2nd,-informed approach
import pandas as pd
dates=np.arange('2020-01-01','2020-03-01',dtype='datetime64[D]')
Mondays=dates[pd.to_datetime(dates).weekday==0]
print(Mondays)

In [ ]:
import numpy as np


A = np.array(['001', '002', '003'], dtype='str')
B = np.array(['XC', 'YC', 'ZC'], dtype='str')

print(np.char.add(A,B))

In [ ]:
A = np.array(['1', '2', '3'], dtype='str')
B = np.array(['000'], dtype='str')
np.char.add(B,A)

In [ ]:
A = np.array(
    [['PLW CDR 11B TEN', 'AMC LPP'], ['CDR PKO KGH', 'CCC QMK']],
    dtype='str',
)
np.char.split(A, ' ')

In [ ]:
A = np.array([['#summer#time#mood'], ['#sport#time']])
A= np.char.replace(A, '#', ' ')
print(A)
A= np.char.strip(A)
print(A)

In [ ]:
import numpy as np
A = np.array(
    [
        ['#summer#time#mood', '#vibe'],
        ['#sport#time', '#good#time'],
        ['#event#summer', '#fast#move'],
    ]
)
counts=np.char.count(A,'time')
print(counts)

In [50]:
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT   PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""

import numpy as np


lines=text.split('\n')
print(f"lines: \n{lines}")
data=[line.split() for line in lines]
print(f"data: \n{data}")
result=np.array(data)
print(f"result: \n{result}")

lines: 
['ALIOR\tPLALIOR00045\t88 860 000\t1 386 216 000\t0,891\t2,16\t14', 'CCC\tPLCCC0000016\t27 918 000\t1 292 603 400\t0,831\t5,28\t42', 'CDPROJEKT\tPLOPTTC00011\t67 348 000\t22 864 646 000\t14,702\t7,39\t7', 'CYFRPLSAT   PLCFRPT00013\t275 301 000\t6 854 994 900\t4,408\t1,17\t14', 'DINOPL\tPLDINPL00011\t47 937 000\t8 916 282 000\t5,733\t9,13\t12', 'JSW\tPLJSW0000015\t52 636 000\t716 902 320\t0,461\t1,51\t24', 'KGHM\tPLKGHM000017\t136 410 000\t9 881 540 400\t6,354\t4,78\t8', 'LOTOS\tPLLOTOS00025\t86 543 000\t5 609 717 260\t3,607\t2,91\t16', 'LPP\tPLLPP0000011\t1 306 000\t7 444 200 000\t4,787\t1,43\t19', 'MBANK\tPLBRE0000012\t12 997 000\t2 830 746 600\t1,820\t0,42\t24', 'ORANGEPL\tPLTLKPL00017\t647 357 000\t4 285 503 340\t2,756\t1,16\t13', 'PEKAO\tPLPEKAO00016\t176 379 000\t9 619 710 660\t6,185\t5,27\t9', 'PGE\tPLPGER000010\t796 776 000\t3 561 588 720\t2,290\t2,88\t18', 'PGNIG\tPLPGNIG00014\t1 624 608 000\t6 072 784 704\t3,905\t1,56\t12', 'PKNORLEN\tPLPKN0000018\t289 049 000\t17 701 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (20,) + inhomogeneous part.

In [51]:
np.set_printoptions(linewidth=150)
result = np.array(
    [
        [
            'ALIOR',
            'PLALIOR00045',
            '88 860 000',
            '1 386 216 000',
            '0,891',
            '2,16',
            '14',
        ],
        [
            'CCC',
            'PLCCC0000016',
            '27 918 000',
            '1 292 603 400',
            '0,831',
            '5,28',
            '42',
        ],
        [
            'CDPROJEKT',
            'PLOPTTC00011',
            '67 348 000',
            '22 864 646 000',
            '14,702',
            '7,39',
            '7',
        ],
        [
            'CYFRPLSAT',
            'PLCFRPT00013',
            '275 301 000',
            '6 854 994 900',
            '4,408',
            '1,17',
            '14',
        ],
        [
            'DINOPL',
            'PLDINPL00011',
            '47 937 000',
            '8 916 282 000',
            '5,733',
            '9,13',
            '12',
        ],
        [
            'JSW',
            'PLJSW0000015',
            '52 636 000',
            '716 902 320',
            '0,461',
            '1,51',
            '24',
        ],
        [
            'KGHM',
            'PLKGHM000017',
            '136 410 000',
            '9 881 540 400',
            '6,354',
            '4,78',
            '8',
        ],
        [
            'LOTOS',
            'PLLOTOS00025',
            '86 543 000',
            '5 609 717 260',
            '3,607',
            '2,91',
            '16',
        ],
        [
            'LPP',
            'PLLPP0000011',
            '1 306 000',
            '7 444 200 000',
            '4,787',
            '1,43',
            '19',
        ],
        [
            'MBANK',
            'PLBRE0000012',
            '12 997 000',
            '2 830 746 600',
            '1,820',
            '0,42',
            '24',
        ],
        [
            'ORANGEPL',
            'PLTLKPL00017',
            '647 357 000',
            '4 285 503 340',
            '2,756',
            '1,16',
            '13',
        ],
        [
            'PEKAO',
            'PLPEKAO00016',
            '176 379 000',
            '9 619 710 660',
            '6,185',
            '5,27',
            '9',
        ],
        [
            'PGE',
            'PLPGER000010',
            '796 776 000',
            '3 561 588 720',
            '2,290',
            '2,88',
            '18',
        ],
        [
            'PGNIG',
            'PLPGNIG00014',
            '1 624 608 000',
            '6 072 784 704',
            '3,905',
            '1,56',
            '12',
        ],
        [
            'PKNORLEN',
            'PLPKN0000018',
            '289 049 000',
            '17 701 360 760',
            '11,382',
            '12,44',
            '8',
        ],
        [
            'PKOBP',
            'PLPKO0000016',
            '857 593 000',
            '18 807 014 490',
            '12,093',
            '10,49',
            '9',
        ],
        [
            'PLAY',
            'LU1642887738',
            '114 151 000',
            '3 696 209 380',
            '2,377',
            '1,47',
            '16',
        ],
        [
            'PZU',
            'PLPZU0000011',
            '568 305 000',
            '17 515 160 100',
            '11,262',
            '6,64',
            '6',
        ],
        [
            'SANPL',
            'PLBZ00000044',
            '33 207 000',
            '5 213 499 000',
            '3,352',
            '1,91',
            '18',
        ],
        [
            'TAURONPE',
            'PLTAURN00011',
            '1 043 590 000',
            '1 252 308 000',
            '0,805',
            '1,21',
            '33',
        ],
    ],
    dtype='<U14',
)

spaces_removed=np.char.strip(result)
result=np.char.replace(spaces_removed, ',', ' ')
print(result)

[['ALIOR' 'PLALIOR00045' '88 860 000' '1 386 216 000' '0 891' '2 16' '14']
 ['CCC' 'PLCCC0000016' '27 918 000' '1 292 603 400' '0 831' '5 28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67 348 000' '22 864 646 000' '14 702' '7 39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275 301 000' '6 854 994 900' '4 408' '1 17' '14']
 ['DINOPL' 'PLDINPL00011' '47 937 000' '8 916 282 000' '5 733' '9 13' '12']
 ['JSW' 'PLJSW0000015' '52 636 000' '716 902 320' '0 461' '1 51' '24']
 ['KGHM' 'PLKGHM000017' '136 410 000' '9 881 540 400' '6 354' '4 78' '8']
 ['LOTOS' 'PLLOTOS00025' '86 543 000' '5 609 717 260' '3 607' '2 91' '16']
 ['LPP' 'PLLPP0000011' '1 306 000' '7 444 200 000' '4 787' '1 43' '19']
 ['MBANK' 'PLBRE0000012' '12 997 000' '2 830 746 600' '1 820' '0 42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647 357 000' '4 285 503 340' '2 756' '1 16' '13']
 ['PEKAO' 'PLPEKAO00016' '176 379 000' '9 619 710 660' '6 185' '5 27' '9']
 ['PGE' 'PLPGER000010' '796 776 000' '3 561 588 720' '2 290' '2 88' '18']
 ['PGNIG' 'PLPGNIG000

In [61]:
np.set_printoptions(linewidth=150)
result = np.array(
    [
        [
            'ALIOR',
            'PLALIOR00045',
            '88860000',
            '1386216000',
            '0.891',
            '2.16',
            '14',
        ],
        [
            'CCC',
            'PLCCC0000016',
            '27918000',
            '1292603400',
            '0.831',
            '5.28',
            '42',
        ],
        [
            'CDPROJEKT',
            'PLOPTTC00011',
            '67348000',
            '22864646000',
            '14.702',
            '7.39',
            '7',
        ],
        [
            'CYFRPLSAT',
            'PLCFRPT00013',
            '275301000',
            '6854994900',
            '4.408',
            '1.17',
            '14',
        ],
        [
            'DINOPL',
            'PLDINPL00011',
            '47937000',
            '8916282000',
            '5.733',
            '9.13',
            '12',
        ],
        [
            'JSW',
            'PLJSW0000015',
            '52636000',
            '716902320',
            '0.461',
            '1.51',
            '24',
        ],
        [
            'KGHM',
            'PLKGHM000017',
            '136410000',
            '9881540400',
            '6.354',
            '4.78',
            '8',
        ],
        [
            'LOTOS',
            'PLLOTOS00025',
            '86543000',
            '5609717260',
            '3.607',
            '2.91',
            '16',
        ],
        [
            'LPP',
            'PLLPP0000011',
            '1306000',
            '7444200000',
            '4.787',
            '1.43',
            '19',
        ],
        [
            'MBANK',
            'PLBRE0000012',
            '12997000',
            '2830746600',
            '1.820',
            '0.42',
            '24',
        ],
        [
            'ORANGEPL',
            'PLTLKPL00017',
            '647357000',
            '4285503340',
            '2.756',
            '1.16',
            '13',
        ],
        [
            'PEKAO',
            'PLPEKAO00016',
            '176379000',
            '9619710660',
            '6.185',
            '5.27',
            '9',
        ],
        [
            'PGE',
            'PLPGER000010',
            '796776000',
            '3561588720',
            '2.290',
            '2.88',
            '18',
        ],
        [
            'PGNIG',
            'PLPGNIG00014',
            '1624608000',
            '6072784704',
            '3.905',
            '1.56',
            '12',
        ],
        [
            'PKNORLEN',
            'PLPKN0000018',
            '289049000',
            '17701360760',
            '11.382',
            '12.44',
            '8',
        ],
        [
            'PKOBP',
            'PLPKO0000016',
            '857593000',
            '18807014490',
            '12.093',
            '10.49',
            '9',
        ],
        [
            'PLAY',
            'LU1642887738',
            '114151000',
            '3696209380',
            '2.377',
            '1.47',
            '16',
        ],
        [
            'PZU',
            'PLPZU0000011',
            '568305000',
            '17515160100',
            '11.262',
            '6.64',
            '6',
        ],
        [
            'SANPL',
            'PLBZ00000044',
            '33207000',
            '5213499000',
            '3.352',
            '1.91',
            '18',
        ],
        [
            'TAURONPE',
            'PLTAURN00011',
            '1043590000',
            '1252308000',
            '0.805',
            '1.21',
            '33',
        ],
    ],
    dtype='<U12',
)

indexes=np.where(np.char.startswith(result[:,0],'P'))
stocks_startswith_P = result[indexes]
print(stocks_startswith_P)

[['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289049000' '17701360760' '11.382' '12.44' '8']
 ['PKOBP' 'PLPKO0000016' '857593000' '18807014490' '12.093' '10.49' '9']
 ['PLAY' 'LU1642887738' '114151000' '3696209380' '2.377' '1.47' '16']
 ['PZU' 'PLPZU0000011' '568305000' '17515160100' '11.262' '6.64' '6']]


In [66]:
np.set_printoptions(linewidth=150)
stocks_startswith_P = np.array(
    [
        [
            'PEKAO',
            'PLPEKAO00016',
            '176379000',
            '9619710660',
            '6.185',
            '5.27',
            '9',
        ],
        [
            'PGE',
            'PLPGER000010',
            '796776000',
            '3561588720',
            '2.290',
            '2.88',
            '18',
        ],
        [
            'PGNIG',
            'PLPGNIG00014',
            '1624608000',
            '6072784704',
            '3.905',
            '1.56',
            '12',
        ],
        [
            'PKNORLEN',
            'PLPKN0000018',
            '289049000',
            '17701360760',
            '11.382',
            '12.44',
            '8',
        ],
        [
            'PKOBP',
            'PLPKO0000016',
            '857593000',
            '18807014490',
            '12.093',
            '10.49',
            '9',
        ],
        [
            'PLAY',
            'LU1642887738',
            '114151000',
            '3696209380',
            '2.377',
            '1.47',
            '16',
        ],
        [
            'PZU',
            'PLPZU0000011',
            '568305000',
            '17515160100',
            '11.262',
            '6.64',
            '6',
        ],
    ],
    dtype='<U12',
)

total_share=np.round(np.sum(stocks_startswith_P[:,4].astype(np.float64)),2)
print(total_share)

49.49


In [77]:
np.set_printoptions(linewidth=160, suppress=True)

wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""

wig_games=wig_games_raw.split('\n')
wig_games=np.array([lines.split('\t') for lines in wig_games], dtype='str')
print(wig_games)

[['Profile' 'Time' 'Course' 'Change' 'Change%' 'Ref.' 'Open' 'Low' 'High' 'Volume' 'Turn' 'Share']
 ['11B (11BIT)' '17 kwi 17:01' '391.00' '+8.00' '(+2.09%)' '383.00' '383.50' '383.00' '394.00' '12 784' '4 994 874' '19.034%']
 ['CDR (CDPROJEKT)' '17 kwi 17:01' '339.50' '+5.30' '(+1.59%)' '334.20' '338.30' '337.00' '344.20' '233 059' '79 245 368' '39.618%']
 ['CIG (CIGAMES)' '17 kwi 17:03' '0.742' '-0.012' '(-1.59%)' '0.754' '0.772' '0.730' '0.772' '1 311 078' '971 459' '1.855%']
 ['PLW (PLAYWAY)' '17 kwi 17:03' '387.50' '+18.00' '(+4.87%)' '369.50' '374.00' '373.00' '388.00' '33 206' '12 661 786' '10.638%']
 ['TEN (TSGAMES)' '17 kwi 17:02' '349.50' '+22.50' '(+6.88%)' '327.00' '332.00' '330.00' '353.50' '39 793' '13 697 060' '28.855%']]


In [81]:
wig_games = np.array(
    [
        [
            'Profile',
            'Time',
            'Course',
            'Change',
            'Change%',
            'Ref.',
            'Open',
            'Low',
            'High',
            'Volume',
            'Turn',
            'Share',
        ],
        [
            '11B(11BIT)',
            '17kwi17:01',
            '391.00',
            '+8.00',
            '(+2.09%)',
            '383.00',
            '383.50',
            '383.00',
            '394.00',
            '12784',
            '4994874',
            '19.034%',
        ],
        [
            'CDR(CDPROJEKT)',
            '17kwi17:01',
            '339.50',
            '+5.30',
            '(+1.59%)',
            '334.20',
            '338.30',
            '337.00',
            '344.20',
            '233059',
            '79245368',
            '39.618%',
        ],
        [
            'CIG(CIGAMES)',
            '17kwi17:03',
            '0.742',
            '-0.012',
            '(-1.59%)',
            '0.754',
            '0.772',
            '0.730',
            '0.772',
            '1311078',
            '971459',
            '1.855%',
        ],
        [
            'PLW(PLAYWAY)',
            '17kwi17:03',
            '387.50',
            '+18.00',
            '(+4.87%)',
            '369.50',
            '374.00',
            '373.00',
            '388.00',
            '33206',
            '12661786',
            '10.638%',
        ],
        [
            'TEN(TSGAMES)',
            '17kwi17:02',
            '349.50',
            '+22.50',
            '(+6.88%)',
            '327.00',
            '332.00',
            '330.00',
            '353.50',
            '39793',
            '13697060',
            '28.855%',
        ],
    ],
    dtype='<U14',
)

print(np.delete(wig_games,[3,4,5,9],axis=1))

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


In [6]:
import numpy as np

np.set_printoptions(linewidth=160, suppress=True)

wig_games = np.array(
    [
        [
            'Profile',
            'Time',
            'Course',
            'Open',
            'Low',
            'High',
            'Turn',
            'Share',
        ],
        [
            '11B(11BIT)',
            '17kwi17:01',
            '391.00',
            '383.50',
            '383.00',
            '394.00',
            '4994874',
            '19.034%',
        ],
        [
            'CDR(CDPROJEKT)',
            '17kwi17:01',
            '339.50',
            '338.30',
            '337.00',
            '344.20',
            '79245368',
            '39.618%',
        ],
        [
            'CIG(CIGAMES)',
            '17kwi17:03',
            '0.742',
            '0.772',
            '0.730',
            '0.772',
            '971459',
            '1.855%',
        ],
        [
            'PLW(PLAYWAY)',
            '17kwi17:03',
            '387.50',
            '374.00',
            '373.00',
            '388.00',
            '12661786',
            '10.638%',
        ],
        [
            'TEN(TSGAMES)',
            '17kwi17:02',
            '349.50',
            '332.00',
            '330.00',
            '353.50',
            '13697060',
            '28.855%',
        ],
    ],
    dtype='<U14',
)

np.savetxt('wig_games.csv', wig_games, delimiter=',', fmt='%s')
wig_games_new=np.loadtxt('wig_games.csv', delimiter=',', dtype=str)
print(wig_games_new)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


In [7]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

playway = playway_raw.split('\n')
playway=np.array([lines.split() for lines in playway])
print(playway)

[['Date,Open,High,Low,Close,Volume']
 ['2020-03-02,305,324.5,283.5,310,64081']
 ['2020-03-03,325.5,340.5,320,340.5,55496']
 ['2020-03-04,324,340.5,315,330,36152']
 ['2020-03-05,344,344,310,315,35992']
 ['2020-03-06,306.5,307,291,305,32539']
 ['2020-03-09,274,291,250,258,79402']
 ['2020-03-10,278,284.5,256,264,35700']
 ['2020-03-11,270,270,238.5,245,60445']
 ['2020-03-12,218,228,196,197,94031']
 ['2020-03-13,210,229,198.8,211,100412']
 ['2020-03-16,205,248,197.8,240.5,50659']
 ['2020-03-17,245,269,232.5,264,99480']
 ['2020-03-18,264,280,251,270,70136']
 ['2020-03-19,267,280,267,279.5,30732']
 ['2020-03-20,297.5,307,280,280.5,43426']
 ['2020-03-23,274,289,258,285,37098']
 ['2020-03-24,305,309,296.5,309,31939']
 ['2020-03-25,313,330,295,304,46724']
 ['2020-03-26,300,309,295.5,300,27213']
 ['2020-03-27,302,306.5,290,296,13466']
 ['2020-03-30,299,300,287,300,10316']
 ['2020-03-31,302.5,309,302,306.5,15698']]


In [12]:
playway = np.array(
    [
        ['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
        ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
        ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
        ['2020-03-04', '324', '340.5', '315', '330', '36152'],
        ['2020-03-05', '344', '344', '310', '315', '35992'],
        ['2020-03-06', '306.5', '307', '291', '305', '32539'],
        ['2020-03-09', '274', '291', '250', '258', '79402'],
        ['2020-03-10', '278', '284.5', '256', '264', '35700'],
        ['2020-03-11', '270', '270', '238.5', '245', '60445'],
        ['2020-03-12', '218', '228', '196', '197', '94031'],
        ['2020-03-13', '210', '229', '198.8', '211', '100412'],
        ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
        ['2020-03-17', '245', '269', '232.5', '264', '99480'],
        ['2020-03-18', '264', '280', '251', '270', '70136'],
        ['2020-03-19', '267', '280', '267', '279.5', '30732'],
        ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
        ['2020-03-23', '274', '289', '258', '285', '37098'],
        ['2020-03-24', '305', '309', '296.5', '309', '31939'],
        ['2020-03-25', '313', '330', '295', '304', '46724'],
        ['2020-03-26', '300', '309', '295.5', '300', '27213'],
        ['2020-03-27', '302', '306.5', '290', '296', '13466'],
        ['2020-03-30', '299', '300', '287', '300', '10316'],
        ['2020-03-31', '302.5', '309', '302', '306.5', '15698'],
    ],
    dtype='<U10',
)

edited=np.delete(playway, [0], axis=1)
playway_values = edited[1:].astype(float)
print(playway_values)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

In [15]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)

print(np.round(playway_values.mean(axis=0),2))

[  283.14   295.25   268.69   282.3  48688.05]


In [18]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)

max_min_diff=playway_values[:,[1]]-playway_values[:,[2]]
playway_values=np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

In [25]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

mask= playway_values[:,3] > 300
print(playway_values[mask].astype(float))

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


In [28]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

print(playway_values[playway_values[:,4].argsort()[::-1]][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


In [37]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

condition = playway_values[:,3] > playway_values[:,0]
state=condition.astype(int)
playway_values=np.concatenate((playway_values, state.reshape(-1,1)), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 