# BROADCASTING - Complete Mastery Set

## The Rules You Must Internalize
Before starting, memorize these 3 rules:

1. Arrays are compatible if dimensions match OR one is 1
2. Dimensions are compared from RIGHT to LEFT
3. Missing dimensions are treated as 1


## BASIC (20 Questions)
### Rule 1: Basic Shape Compatibility

**Q1. Will these broadcast? Why or why not?**
```python
a.shape = (6, 1)
b.shape = (5,)
```

**Q2. Will these broadcast? If yes, what's the output shape?**
```python
a.shape = (3, 4, 5)
b.shape = (4, 5)
```

**Q3. Will these broadcast? Explain the rule violation.**
```python
a.shape = (2, 3, 4)
b.shape = (3, 5)
```

**Q4. What's the broadcasted shape of:**
```python
a.shape = (1, 5, 1, 6)
b.shape = (3, 1, 6, 1)
```

(3,5,6,6)

**Q5. What's the broadcasted shape of:**
```python
a.shape = (10, 1, 10)
b.shape = (1, 10, 1)
```

### Adding Scalars and 1D Arrays

**Q6. Create a 3×4 array of zeros. Add the scalar 5 to it. What shape is the result? Why does this work?**

In [4]:
import numpy as np
arr_zero=np.zeros((3,4)) + 5
print(arr_zero)
# this works because a scalar is treated as a 1D-array of one element. and broadcasting works with all scalars

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


**Q7. Create a 5×5 array of ones. Create a 1D array of 5 numbers [1,2,3,4,5]. Add them. What shape is the result? Explain.**

In [7]:
arr_ones=np.ones((5,5))
arr=np.array([1,2,3,4,5])
result=arr_ones+arr
print(result.shape)
print(result)

(5, 5)
[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]]


**Q8. Create a 4×3 array of random integers. Add a 1D array of shape (4,). What happens? Why?**

In [9]:
arr=np.random.randint(1,11,size=12).reshape(4,3)
print(f"arr: \n{arr}")
arr1d=np.random.randint(1,11,size=4)
print(f"arr1d: \n{arr1d}")
print(f"adding both: \n{arr+arr1d}")

# error will occur because rule 2 is violated that the dimension which needs to be broadcasted is not 1

arr: 
[[ 1  7  8]
 [ 7  1 10]
 [ 1  1  6]
 [ 1  4  8]]
arr1d: 
[10  7  1  7]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

**Q9. Create a 4×3 array. Add a 1D array of shape (3,). Compare with Q8. Why does one work and not the other?**

In [11]:
arr1=np.random.randint(1,11,size=12).reshape(4,3)
print(f"arr1: \n{arr1}")
arr2=np.random.randint(1,11,size=3)
print(f"arr2: \n{arr2}")
print(f"result: \n{arr1+arr2}")

# this one works because it has 1 as dimension which needs to be broadcasted

arr1: 
[[ 7  5  2]
 [ 2 10  2]
 [ 1  9  6]
 [ 5  8  1]]
arr2: 
[ 5 10  4]
result: 
[[12 15  6]
 [ 7 20  6]
 [ 6 19 10]
 [10 18  5]]


**Q10. Create a 2×3×4 array. Multiply by a scalar 2.5. Write the broadcasting rule that explains this.**

In [12]:
arr1=np.random.randint(1,11,size=24).reshape(2,3,4)
print(f"arr1: \n{arr1}")
result=arr1*2.5
print(f"result:\n{result}")


arr1: 
[[[10 10  2  4]
  [ 8  7  8  8]
  [ 6  1  9  7]]

 [[ 3  4 10  6]
  [ 1  4  4  3]
  [ 3  5  6  9]]]
result:
[[[25.  25.   5.  10. ]
  [20.  17.5 20.  20. ]
  [15.   2.5 22.5 17.5]]

 [[ 7.5 10.  25.  15. ]
  [ 2.5 10.  10.   7.5]
  [ 7.5 12.5 15.  22.5]]]


### The newaxis Trick

**Q11. You have `a.shape = (10,)` and `b.shape = (10, 10)`. You want to add a to each row of b. How do you reshape a using `np.newaxis`?**

In [13]:
# for reshaping

a=np.random.randint(1,11,size=10)
b=np.random.randint(1,50,size=100).reshape(10,10)

# incompatible addinig:
# res=a+b

# compatible adding using np.newaxis
a[:,np.newaxis]

# or
# a[:,None]

result=a+b
print(result)

[[34 54 42 46 32 33  8 44 24 30]
 [49  8 39 23 21 49  7 25 16 21]
 [ 8 26 42 30 18 32 21 35 48  6]
 [10  9 14 33 50 11 50 42 35  4]
 [21 38 21 24 18 23 40 17 39 11]
 [ 2 22 10 44  9 56 39  7 23 13]
 [19 14 31 19  9 46 19 16 16 16]
 [ 5 28 35 30 38 47 49 18 13  7]
 [30 25 29 56  6 14  9  3 12 44]
 [33 26  9 58  8 34 51 21 30 50]]


**Q12. You have `a.shape = (5, 4)` and `b.shape = (5,)`. You want to subtract b from each column of a. Reshape b correctly.**

In [ ]:
b[:,None]

**Q13. You have `a.shape = (3, 4, 5)` and `b.shape = (4, 1)`. Can they broadcast? If not, add `np.newaxis` to make them broadcast.**

In [ ]:
b[np.newaxis,:,:]

**Q14. Convert a 1D array of shape (12,) to shapes: (12,1), (1,12), (12,1,1), (1,12,1), (1,1,12) using `np.newaxis`.**

In [17]:
arr=np.random.randint(1,13,size=12)

arr1=arr[:,np.newaxis]
print(arr1.shape)

arr2=arr[np.newaxis,:]
print(arr2.shape)

arr3=arr[:,np.newaxis,None]
print(arr3.shape)

arr4=arr[np.newaxis,:,np.newaxis]
print(arr4.shape)

arr5=arr[None,None,:]
print(arr5.shape)

(12, 1)
(1, 12)
(12, 1, 1)
(1, 12, 1)
(1, 1, 12)


**Q15. You have latitude (100,) and longitude (120,) arrays. Create a 2D grid of shape (100, 120) where each element is (lat, lon) using broadcasting and `np.newaxis`.**

In [21]:
lat=np.random.randint(1,101,size=100)
lon=np.random.randint(1,121, size=120)
print(lat.shape,lon.shape)

dtype=[('lat',float),('lon',float)]
grid=np.empty((100,120),dtype=dtype)
grid['lat']=lat[:,np.newaxis]
grid['lon']=lon[np.newaxis,:]
print(grid)

(100,) (120,)
[[( 6., 118.) ( 6.,  44.) ( 6.,  18.) ... ( 6.,  34.) ( 6.,  91.)
  ( 6.,  90.)]
 [(18., 118.) (18.,  44.) (18.,  18.) ... (18.,  34.) (18.,  91.)
  (18.,  90.)]
 [(60., 118.) (60.,  44.) (60.,  18.) ... (60.,  34.) (60.,  91.)
  (60.,  90.)]
 ...
 [(65., 118.) (65.,  44.) (65.,  18.) ... (65.,  34.) (65.,  91.)
  (65.,  90.)]
 [(45., 118.) (45.,  44.) (45.,  18.) ... (45.,  34.) (45.,  91.)
  (45.,  90.)]
 [(42., 118.) (42.,  44.) (42.,  18.) ... (42.,  34.) (42.,  91.)
  (42.,  90.)]]


### Practical Operations

**Q16. Create a 5×5 identity matrix. Create a 1D array of 5 numbers. Multiply the identity matrix by the array. Explain what happens.**

In [27]:
arr1=np.random.randint(1,26,size=25).reshape(5,5)
arr2=np.array([1,2,3,4,5])
res=arr1*arr2
print(res)
# broadcasting happens.. arr2 gets a new rows-dimension, then it gets stretched and gets multiplied

[[ 23   8  75  72  45]
 [  1  20   3  64  40]
 [  7  12  75  32  75]
 [  4  14  57  60 120]
 [  4   2  30  24  55]]


**Q17. Create a (100, 50) array of random data. Create a (50,) array of column weights. Multiply each column by its weight using broadcasting.**

In [ ]:
arr1=np.random.randint(1,501,size=500).reshape(100,50)
arr2=np.random.randint(1,51,size=50)

**Q18. Create a (100, 50) array. Create a (100,) array of row means. Subtract the row mean from each row. Verify each row now has mean ≈ 0.**

In [ ]:
import numpy as np
arr1=np.random.randint(1,501,size=500).reshape(100,50)
arr2=np.random.randint(1,101,size=100).reshape(100,)


**Q19. Create temperature data: shape (365, 180, 360) for (day, lat, lon). Create a climatology: shape (180, 360) for mean annual temp. Calculate daily anomalies in one line.**

**Q20. Create precipitation data: shape (12, 73, 144) for (month, lat, lon). Create monthly weights: shape (12, 1, 1). Calculate weighted average across months.**

## ADVANCED (10 Questions)
### Memory & Performance Deep Dive

**Q21. Memory Explosion Trap**
```python
a = np.random.rand(1000, 1, 1000)
b = np.random.rand(1, 1000, 1)
```
What is the shape after broadcasting? How much memory would the broadcasted result occupy (in GB)? Why is this dangerous? How would you avoid it?

**Q22. In-place Broadcasting**
Can you do in-place operations with broadcasting? Test this:
```python
a = np.ones((100, 100))
b = np.arange(100)
a += b  # What shape does b broadcast to? Does this work?
a *= b  # What about this?
```
Explain the difference between `+` and `*` with broadcasting in-place.

**Q23. Strided Broadcasting Internals**
```python
a = np.arange(12).reshape(3, 4)
b = np.array([10, 20, 30])
c = a + b[:, np.newaxis]
```
Without running, describe the memory layout of c. How many times is each element of b accessed? What are the strides of the result?

### Complex Broadcasting Patterns

**Q24. Outer Product Without Outer**
Implement `np.outer(a, b)` using only broadcasting and `np.newaxis` for:
```python
a = np.array([1,2,3,4])
b = np.array([10,20,30])
```
Now generalize to 3D: create a 3×4×2 array where `result[i,j,k] = a[i] * b[j] * c[k]` using broadcasting.

**Q25. Distance Matrix Challenge**
Create a distance matrix for 1000 random 2D points WITHOUT loops. Given:
```python
points = np.random.rand(1000, 2)  # 1000 points, each (x,y)
```
Create a 1000×1000 matrix where `dist[i,j] = sqrt((x_i-x_j)² + (y_i-y_j)²)` using only broadcasting. What's the memory complexity? Is this feasible for 100,000 points?

**Q26. Conditional Broadcasting**
You have:
```python
data = np.random.rand(50, 40, 30)  # (time, lat, lon)
thresholds = np.array([0.2, 0.5, 0.8])  # 3 different thresholds
```
Create a boolean array of shape (3, 50, 40, 30) where each slice applies one threshold to ALL data points. Do this WITHOUT loops. Then count how many time steps exceed each threshold at each grid point.

### Real Climate Scenarios

**Q27. Latitude Weighting with Broadcasting**
Global temperature data: shape (100 time steps, 180 lat, 360 lon)
Latitude array: shape (180,) with values from -90° to 90°
Cosine weights for area: `weights = cos(lat * pi/180)`

Task:
- Apply weights to ALL grid cells at each latitude (all longitudes get same weight)
- Calculate global weighted mean for each time step
- Calculate global weighted mean for the entire dataset
- Do all operations using broadcasting ONLY (no loops, no manual reshaping of weights to full grid)

**Q28. ENSO Composite Analysis**
You have 50 years of monthly SST data: shape (600 months, 180 lat, 360 lon)
ENSO index: shape (600,) with values (negative = La Niña, positive = El Niño)

Create composites:
- Mean SST during strong El Niño (index > 1.0)
- Mean SST during strong La Niña (index < -1.0)
- Difference map (El Niño - La Niña)

Requirements:
- Use boolean indexing to extract month indices
- Use broadcasting to compute means
- NO loops over space
- Handle potential NaN values

**Q29. Lead-Lag Correlations**
You have:
```python
sst = np.random.rand(1000, 180, 360)  # 1000 months of SST
nino34 = np.random.rand(1000)  # Nino3.4 index
```
Calculate correlation between Nino3.4 and SST at lags -12 to +12 months (i.e., SST leads and lags the index).

Challenge: Create a (25, 180, 360) array where each slice is correlation at a specific lag using broadcasting and `np.roll()`. No loops over space.

**Q30. The Ultimate Broadcasting Challenge: 4D Anomaly Calculation**
You have 30 years of daily data: shape (30, 365, 73, 144) for (year, day, lat, lon)
Calculate:
- Daily climatology (mean for each day-of-year across all years): shape (365, 73, 144)
- Daily anomalies for each year: shape (30, 365, 73, 144)
- Seasonal cycle of anomalies (mean anomaly for each month)
- Remove the seasonal cycle to get residuals

Do ALL steps using broadcasting. No reshaping that copies data unnecessarily. Track memory usage.

Bonus for Q30: What's the minimum memory required if original data is float32 (≈ 30×365×73×144 × 4 bytes ≈ 460 MB)? Can you do this without creating intermediate arrays that double memory?